/*
 * This source file was generated by the Gradle 'init' task
 */
package edu.wofford;
import java.util.Scanner;


public class App {
    public static void print(Sudoku s) {
        for (int i = 0; i < 4; i++) {
            for (int j = 0; j < 4; j++) {
                String v = s.getNumber(i, j) > 0? String.valueOf(s.getNumber(i, j)) : " ";
                System.out.print(" " + v + " ");
                if (j == 0 || j == 2) {
                    System.out.print("|");
                } else if (j == 1) {
                    System.out.print("||");
                }
            }
            System.out.println();
            if (i == 0 || i == 2) {
                System.out.println("---+---++---+---");
            } else if (i == 1) {
                System.out.println("=======++=======");
            }
        }
    }

    public static boolean isSolved(Sudoku s) {
        for (int i = 0; i < 4; i++) {
            if (s.getRowSum(i) != 10) { return false; }
        }
        return true;
    }

    public static void main(String[] args) {
    	// There's nothing to implement here.
    	// This is just an example of how the class might be used.
        int[][] brd = {
            {0,4,0,1},
            {3,0,0,0},
            {0,0,0,4},
            {0,0,0,0},
        };
        Scanner scanner = new Scanner(System.in);
        Sudoku sud = new Sudoku(brd);
        while (!isSolved(sud)) {
            print(sud);
            System.out.println("row col val: ");
            int row = scanner.nextInt();
            int col = scanner.nextInt();
            int val = scanner.nextInt();
            if (sud.isLegal(row, col, val)) {
                sud.setNumber(row, col, val);
            }
        }
    }
}
