/*
 * This source file was generated by the Gradle 'init' task
 */
package edu.wofford;


public class App {
    public static void main(String[] args) {
    	// There's nothing to implement here.
    	// This is just an example of how the class might be used.
        SlidingPuzzle p = new SlidingPuzzle();
        System.out.println(p);
        p.slide(SlidingPuzzle.Direction.S);
        System.out.println(p);
        p.slide(SlidingPuzzle.Direction.W);
        System.out.println(p);
    }
}
